-- 30일 동안 대여 가능한 세단 or SUV
WITH AVAIL AS (
	SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
     AND NOT EXISTS (
     	SELECT 1
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
         WHERE H.CAR_ID = C.CAR_ID
         -- "겹치는 예약 제외"
         	AND H.START_DATE <= DATE('2022-11-30')
         	AND H.END_DATE >= DATE('2022-11-01')
     )
), 
PLAN_30 AS (
	SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

-- 30일 요금 * (1 - 할인율/100)
SELECT A.CAR_ID, A.CAR_TYPE, FLOOR((A.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100))) AS FEE
FROM AVAIL A
JOIN PLAN_30 P ON P.CAR_TYPE = A.CAR_TYPE
WHERE FLOOR((A.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100))) >= 500000
	AND FLOOR((A.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100))) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC

