/*WITH MAY AS (
	SELECT *
    FROM FOOD_ORDER
    WHERE 
)
*/
SELECT 
	P.PRODUCT_ID, 
    P.PRODUCT_NAME,
    SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE >= DATE('2022-05-01')
	AND O.PRODUCE_DATE <= DATE('2022-05-31')
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID