WITH J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
	FROM JULY
	GROUP BY FLAVOR)
    
SELECT F.FLAVOR
FROM FIRST_HALF AS F
LEFT JOIN J ON J.FLAVOR = F.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.JULY_SUM) DESC
LIMIT 3