WITH RECURSIVE HOURS AS (
	SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

-- NULL이 아닌 행
SELECT HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS O ON HOUR(O.DATETIME) = H.HOUR
GROUP BY HOUR
ORDER BY HOUR