WITH AVG_SCORE AS (
	SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT 
	E.EMP_NO,
    E.EMP_NAME,
    CASE
    	WHEN A.AVG_SCORE >= 96 THEN 'S'
        WHEN A.AVG_SCORE >= 90 THEN 'A'
        WHEN A.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
		WHEN A.AVG_SCORE >= 96 THEN ROUND(E.SAL * 0.2, 0)
        WHEN A.AVG_SCORE >= 90 THEN ROUND(E.SAL * 0.15, 0)
        WHEN A.AVG_SCORE >= 80 THEN ROUND(E.SAL * 0.1, 0)
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN AVG_SCORE A ON A.EMP_NO = E.EMP_NO
ORDER BY E.EMP_NO