WITH REVIEWS AS (
	SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
BEST AS (	-- 최다 리뷰 회원(동률 허용)
	SELECT MEMBER_ID
    FROM REVIEWS
    WHERE CNT = (SELECT MAX(CNT) FROM REVIEWS)
)


SELECT 
	M.MEMBER_NAME, 
    R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN BEST B ON B.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
