-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
WHERE H.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
	AND C.CAR_TYPE = '세단'
ORDER BY H.CAR_ID DESC