-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
	AND F.PRICE = (
    	SELECT MAX(F2.PRICE)
        FROM FOOD_PRODUCT F2
        WHERE F2.CATEGORY = F.CATEGORY
    )
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC